# Pipeline de CI para FacturaYa Backend
# Solo ejecuta build, NO hace deploy (deploy lo hace Render.com)

trigger:
  branches:
    include:
      - main

pool:
  name: 'Default'

stages:
  - stage: Build
    displayName: 'Build and Validate'
    jobs:
      - job: BuildJob
        displayName: 'Build Application'
        steps:
          - script: |
              node --version
              npm --version
            displayName: 'Check Node and npm versions'
          
          - script: |
              echo "Installing dependencies..."
              npm ci
            displayName: 'Install Dependencies'

          - script: |
              echo "Building TypeScript project..."
              npm run build
            displayName: 'Build Project'

          - script: |
              echo "Verifying build output..."
              ls -la dist/
            displayName: 'Verify Build Output'

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Build Artifacts'
            inputs:
              PathtoPublish: 'dist'
              ArtifactName: 'build-output'
              publishLocation: 'Container'